<!DOCTYPE html>
<html>
    <head>
        <meta charset=utf-8>
        <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
        <title>Валюта</title>
        <link rel=stylesheet type=text/css href=/styles/bootstrap.min.css>
        <link rel=stylesheet type=text/css href=/styles/bootstrap-grid.min.css>
        <link rel=stylesheet type=text/css href=/styles/bootstrap-reboot.min.css>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel=stylesheet>
        <link href=/styles/app.css rel=stylesheet>
    </head>
    <body>
        <div id=app></div>
        <script type=text/javascript src=/scripts/app.js></script>
    </body>
</html>